### ISSUE TITLE
Delete actions not accepting an array of paths

### ISSUE THREAD

**Issue by arqex** [gregnb/filemanager-webpack-plugin#39]
Hey thanks for the plugin, it's just what I was looking for!

## Config

```
new fm({
	onStart: [{
		delete: [ 'mydir/' ]
	}]
})
```

## Issue
Delete is not working when passing an array of strings. I am getting the error:

```
"TypeError: Cannot read property 'replace' of undefined
    at FileManagerPlugin.replaceHash (D:\projects\docker-containers\ycbm-app\node_modules\filemanager-webpack-plugin\lib\index.js:376:23)
    at D:\projects\docker-containers\ycbm-app\node_modules\filemanager-webpack-plugin\lib\index.js:419:61
    at Array.forEach (<anonymous>)
    at D:\projects\docker-containers\ycbm-app\node_modules\filemanager-webpack-plugin\lib\index.js:398:23
    at Array.forEach (<anonymous>)
    at FileManagerPlugin.parseFileOptions (D:\projects\docker-containers\ycbm-app\node_modules\filemanager-webpack-plugin\lib\index.js:394:28)
    at D:\projects\docker-containers\ycbm-app\node_modules\filemanager-webpack-plugin\lib\index.js:357:82
    at Array.map (<anonymous>)
    at FileManagerPlugin.checkOptions (D:\projects\docker-containers\ycbm-app\node_modules\filemanager-webpack-plugin\lib\index.js:356:29)
    at comp (D:\projects\docker-containers\ycbm-app\node_modules\filemanager-webpack-plugin\lib\index.js:457:16)
    at SyncHook.eval [as call] (eval at create (D:\projects\docker-containers\ycbm-app\node_modules\tapable\lib\HookCodeFactory.js:17:12), <anonymous>:7:1) ... 
```

What's happening is that on the delete action the plugin is doing `_this2.replaceHash(actionItem.source)` and source is not defined, actionItem is just the path to the dir to delete.

I don't know if it's a docs problem or a library problem but it took me some time to find it.

## Your Environment

| Tech         | Version |
|--------------|---------|
| filemanager-plugin-webpack  |     v2.0    |
| node        |   v8.11.1      |
| OS      |   MacOs High Sierra   |

**Comment by selbekk** [comment]
Yeah I noticed this too. I'm working on a PR to fix it

**Comment by gregnb** [comment]
You're right it is indeed a bug. Thank you
